version: 2

sources:
  - name: source_raw # this is the source_name
    database: mock_project_db
    schema: raw
    tables:
      - name: line_item_supply # this is the table_name
        columns:
          - name: orderkey
            tests:
              - not_null
          - name: partkey
            tests: 
              - not_null
          - name: suppkey
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null
          - name: extendedprice
            tests:
              - not_null
          - name: shipinstruct
            tests:
              - accepted_values:
                  values: ['COLLECT COD', 'NONE', 'DELIVER IN PERSON', 'TAKE BACK RETURN']
          - name: shipmode
            tests:
             - accepted_values:
                values: ['AIR', 'RAIL', 'MAIL', 'REG AIR', 'TRUCK', 'FOB', 'SHIP']

      - name: order_summary
        columns:
          - name: custkey
            tests:
              - not_null
          - name: orderkey
            tests:
              - not_null
          - name: customer
            tests:
              - not_null
          - name: cust_address
            tests:
              - not_null
          - name: totalprice
            tests:
              - not_null
          - name: orderpriority
            tests:
              - accepted_values:
                  values: ['2-HIGH', '3-MEDIUM', '1-URGENT', '4-NOT SPECIFIED' , '5-LOW'] 
                                          
      - name: part_supply_supplier
        columns:
          - name: partkey
            tests:
              - not_null
          - name: suppkey
            tests:
              - not_null
          - name: part_name
            tests:
              - not_null
          - name: retailprice
            tests:
              - not_null
          - name: address
            tests:
              - not_null        
  
  